config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :rental do
    member do
      get :confirm_email
    end
  end
  root "rental#index"
  resources :vehicle
  resources :property
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < Rental
    has_one :property_detail
    belongs_to :user
    has_one_attached :main_image
end

app/models/property_detail.rb
class PropertyDetail < ApplicationRecord
    belongs_to :property
  
end

app/models/rental.rb
class Rental < ApplicationRecord
    belongs_to :user
    has_one_attached :main_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable\
  has_many :rentals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/models/vehicle.rb
class Vehicle < Rental
    has_one :vehicle_detail
    belongs_to :user
    has_one_attached :main_image
end

app/models/vehicle_detail.rb
class VehicleDetail < ApplicationRecord
    belongs_to :vehicle
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
    def index

    end
    def new
        @property = Property.new
    end
    def create
        puts ("following is user id")
        property = Property.create(title: params[:title], description: params[:description], duration: params[:duration], price: params[:price],user_id: current_user.id, main_image: params[:main_image])
       
        
        redirect_to rental_index_path


    end


end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
    before_action :authenticate_user!
    def index
        @rentals = Rental.all

    end
    def new

    end

    def create
        if params[:property_type] == 'Property'
            property = Rental.new(property_params)
            if property.save
                puts "Property saved successfully"
                property.create_property_detail(property_params)
                render :new
            end
        elsif params[:property_type] == 'Vehicle'
            vehicle = Rental.create(property_params)
            vehicle.create_property_detail(property_params)
        end

    end
    def show
        p=Rental.find_by(id: params[:id])
        if p.type == "Property"
            @detail = p.property_detail
            puts "rrrrrr"
            puts @detail
            puts "hhhhhhhhhhh"
        elsif p.type == "Vehicle"
            @detail= p.vehicle_detail
           
        end


    end

    private
  def property_params
    params.require(:property).permit(:title, :description, :duration, :price, :area, :location, :bedrooms, :main_image, :capacity, :engine, :time, :model, :wheel, :color, :mileage, :main_image)
  end
end

app/controllers/vehicle_controller.rb
class VehicleController < ApplicationController

    def index

    end
    def create

    end
    def new
        @vehicle = Vehicle.new
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/partials/_rental.html.erb
<%= image_tag rental.main_image%>
<%= rentals.title%>
<%= rentals.description%>
<%= rentals.type%>
<%= rentals.duration%>
<%= rentals.price%>

app/views/property/new.html.erb
<h1>Add Property for Rent</h1>

<%= form_with url: "/property", method: :post, data: { turbo: false } do |form| %>
  <%= form.label :title, "Title" %>
  <%= form.text_field :title %>
  <%= form.label :description, "Description" %>
  <%= form.text_field :description %>
  <%= form.label :duration, "Duration" %>
  <%= form.text_field :duration %>
  <%= form.label :price, "Price" %>
  <%= form.text_field :price %>

  <%= form.select :property_type, options_for_select(["Property", "Vehicle"]), {}, { id: "property-type-select" } %>

  <div id="Property" style="display: none;">
    <%= form.label :area, "Area" %>
    <%= form.text_field :area %>
    <%= form.label :location, "Location" %>
    <%= form.text_field :location %>
    <%= form.label :bedrooms, "Bedrooms" %>
    <%= form.text_field :bedrooms %>
    <%= form.label :main_image_property %>
    <%= form.file_field :main_image %>
  </div>

  <div id="Vehicle" style="display: none;">
    <%= form.label :capacity, "Capacity" %>
    <%= form.text_field :capacity %>
    <%= form.label :engine, "Engine" %>
    <%= form.text_field :engine %>
    <%= form.label :time, "For how much time" %>
    <%= form.text_field :time %>
    <%= form.label :model, "Model" %>
    <%= form.text_field :model %>
    <%= form.label :wheel, "Wheel" %>
    <%= form.text_field :wheel %>
    <%= form.label :color, "Color" %>
    <%= form.text_field :color %>
    <%= form.label :mileage, "Mileage" %>
    <%= form.text_field :mileage %>
    <%= form.label :main_image_vehicle %>
    <%= form.file_field :main_image%>
  </div>

  <%= form.submit %>
<% end %>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    $('#property-type-select').change(function() {
      var selectedValue = $(this).val();
      $('#Property, #Vehicle').hide();
      $('#' + selectedValue).show();
    });
  });
</script>

app/views/rental/index.html.erb
<h1>Here all rentals will be shown.</h1>
<button><%= link_to "Add for Rent", new_rental_path%></button>
<%= button_to "logout", destroy_user_session_path, method: :delete  %>



<% @rentals.each do |rental| %>
    <% if rental.main_image.present? %>
    <%= image_tag rental.main_image %>
  <% end %>
    <%= rental.title%>
    <%= rental.description%>
    <%= rental.type%>
    <%= rental.duration%>
    <%= rental.price%>
    <%= link_to "Details", rental_path(rental.id)%>
    <%= rental.id%>
<% end %>

app/views/rental/new.html.erb
<h1>Add for Rent</h1>

<%= form_with url: "/property", method: :post, data: { turbo: false } do |form| %>
  <%= form.label :title, "Title" %>
  <%= form.text_field :title %>
  <%= form.label :description, "Description" %>
  <%= form.text_field :description %>
  <%= form.label :duration, "Duration" %>
  <%= form.text_field :duration %>
  <%= form.label :price, "Price" %>
  <%= form.text_field :price %>

  <%= form.select :property_type, options_for_select(["Property", "Vehicle"]), {}, { id: "property-type-select" } %>

  <div id="Property" >
    <%= form.label :area, "Area" %>
    <%= form.text_field :area %>
    <%= form.label :location, "Location" %>
    <%= form.text_field :location %>
    <%= form.label :bedrooms, "Bedrooms" %>
    <%= form.text_field :bedrooms %>
    <%= form.label :main_image %>
    <%= form.file_field :main_image %>
  </div>

  <div id="Vehicle" style="display: none;" >
    <%= form.label :capacity, "Capacity" %>
    <%= form.text_field :capacity %>
    <%= form.label :engine, "Engine" %>
    <%= form.text_field :engine %>
    <%= form.label :time, "For how much time" %>
    <%= form.text_field :time %>
    <%= form.label :model, "Model" %>
    <%= form.text_field :model %>
    <%= form.label :wheel, "Wheel" %>
    <%= form.text_field :wheel %>
    <%= form.label :color, "Color" %>
    <%= form.text_field :color %>
    <%= form.label :mileage, "Mileage" %>
    <%= form.text_field :mileage %>
    <%= form.label :main_image_vehicle %>
    <%= form.file_field :main_image %>
  </div>

  <%= form.submit %>
<% end %>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    $('#property-type-select').change(function() {
      var selectedValue = $(this).val();
      $('#Property, #Vehicle').hide();
      $('#' + selectedValue).show();
    });
  });
</script>

app/views/rental/show.html.erb
<%= @detail.id%>

app/views/vehicle/new.html.erb
<h1>Add the Vehicle Below to rent</h1>
<h1>Add Property for Rent</h1>

<%=form_with url: "/vehicle" , method: :post , data: {turbo: false} do |form| %>
 <%= form.label :title, "Title" %>
 <%= form.text_field :title %>
 <%= form.label :description, "Description" %>
 <%= form.text_field :description %>
 <%= form.label :duration, "Duration" %>
 <%= form.text_field :duration %>
 <%= form.label :price,"Price" %>
 <%= form.text_field :price %>
 
 <%= form.label :area,"Area" %>
 <%= form.text_field :area %>
 <%= form.label :location,"Location" %>
 <%= form.text_field :location %>
 <%= form.label :bedrooms,"Bedrooms" %>
 <%= form.text_field :bedrooms %>

 <%= form.label :main_image %>
<%= form.file_field :main_image %>
 <%= form.submit %>
<% end %>